# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ned',
            name='ned_prefix',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
    ]
