# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_ui', '0002_ned_ned_prefix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ned',
            old_name='ned_prefix',
            new_name='prefix',
        ),
    ]
